### ISSUE TITLE
7/10/2024 - Private RAG Deployment & Cost

### ISSUE THREAD

**Issue by jperiodlangley** [HSV-AI/presentations#100]
# Complete the following items to get a presentation ready for Huntsville AI

## Description

<html>
<body>

We have been covering a series this year based on how a RAG works, and how to build one. Now it's time to look at what it will cost to deploy it!BLUF: If you have constraints that require you to host your own LLM instead of using services such as OpenAI, Anthropic, or Google - this is going to get expensive.The baseline that we will be using to derive requirements and prices will be the a subset documents that we have been using along the way from NASA. To start, I have pulled 500 of these documents which total 109,516 paragraphs and 4,254,032 words.We will start with a basic use case with using OpenAI GPT4o and a Weaviate hosted vector store. We will move from there to a self hosted solution for all of the components and add up the month cost associated. | We have been covering a series this year based on how a RAG works, and how to build one. Now it's time to look at what it will cost to deploy it!BLUF: If you have constraints that require you to host your own LLM instead of using services such as OpenAI, Anthropic, or Google - this is going to get expensive.The baseline that we will be using to derive requirements and prices will be the a subset documents that we have been using along the way from NASA. To start, I have pulled 500 of these documents which total 109,516 paragraphs and 4,254,032 words.We will start with a basic use case with using OpenAI GPT4o and a Weaviate hosted vector store. We will move from there to a self hosted solution for all of the components and add up the month cost associated.
-- | --
We have been covering a series this year based on how a RAG works, and how to build one. Now it's time to look at what it will cost to deploy it!BLUF: If you have constraints that require you to host your own LLM instead of using services such as OpenAI, Anthropic, or Google - this is going to get expensive.The baseline that we will be using to derive requirements and prices will be the a subset documents that we have been using along the way from NASA. To start, I have pulled 500 of these documents which total 109,516 paragraphs and 4,254,032 words.We will start with a basic use case with using OpenAI GPT4o and a Weaviate hosted vector store. We will move from there to a self hosted solution for all of the components and add up the month cost associated.

<br class="Apple-interchange-newline">
</body>
</html>

## Tasks

- [x] Description Completed
- [ ] Image Attached
- [ ] HSV.AI Event Created - [hsv.ai](https://hsv.ai/events)
- [ ] Facebook Event Created - [Facebook Group](https://www.facebook.com/groups/hsvai/)
- [ ] LinkedIn Event Created - [Huntsville AI](https://www.linkedin.com/company/huntsville-ai)

# Adding material to the presentations repository

Add the file to present (prefer Jupyter Notebooks or Markdown formated files) to the folder structure. For multiple files, create a directory following the naming convention and add the files to it.

## Naming convention

We use a convention of starting the filenames with a date (year/month/day) so that the files are still sorted by date even when in alphabetical format.

YYMMDD_Session_Description.extension

**Comment by jperiodlangley** [comment]
![Private RAG](https://github.com/user-attachments/assets/8067fb7b-51f2-4011-ab71-05c18fb3be85)
